default-lease-time  3600;
max-lease-time      7200;
authoritative;      
log-facility local7;

# VLAN 20 — Staff i TPV (192.168.20.0/24)
subnet 192.168.20.0 netmask 255.255.255.0 {
    range 192.168.20.50 192.168.20.100;

    option subnet-mask          255.255.255.0;
    option broadcast-address    192.168.20.255;
    option routers              192.168.20.1;
    option domain-name-servers  192.168.10.10;   # DNS intern
    option domain-name          "elbongust.local";
    option ntp-servers          192.168.10.10;

    default-lease-time  28800;   # 8 hores (durada d'un torn de treball)
    max-lease-time      43200;   # 12 hores màxim

    # --- IPs estàtiques per dispositius de staff ---
    # TPV de la barra
    host tpv-barra {
        hardware ethernet AA:BB:CC:DD:EE:01;
        fixed-address 192.168.20.10;
        option host-name "tpv-barra";
    }

    # Tauleta cambrer 1 (sala)
    host tablet-cambrer-01 {
        hardware ethernet AA:BB:CC:DD:EE:11;
        fixed-address 192.168.20.21;
        option host-name "tablet-c01";
    }

    # Tauleta cambrer 2 (sala)
    host tablet-cambrer-02 {
        hardware ethernet AA:BB:CC:DD:EE:12;
        fixed-address 192.168.20.22;
        option host-name "tablet-c02";
    }

    # Tauleta cambrer 3 (terrassa)
    host tablet-cambrer-03 {
        hardware ethernet AA:BB:CC:DD:EE:13;
        fixed-address 192.168.20.23;
        option host-name "tablet-c03";
    }

    # Impressora cuina
    host impressora-cuina {
        hardware ethernet AA:BB:CC:DD:EE:21;
        fixed-address 192.168.20.30;
        option host-name "impressora-cuina";
    }

    # Impressora barra
    host impressora-barra {
        hardware ethernet AA:BB:CC:DD:EE:22;
        fixed-address 192.168.20.31;
        option host-name "impressora-barra";
    }
}

# VLAN 30 — Clients (192.168.30.0/24)
subnet 192.168.30.0 netmask 255.255.255.0 {
    range 192.168.30.50 192.168.30.200;

    option subnet-mask          255.255.255.0;
    option broadcast-address    192.168.30.255;
    option routers              192.168.30.1;
    option domain-name-servers  8.8.8.8, 8.8.4.4;

    default-lease-time  3600;    # 1 hora
    max-lease-time      7200;

}

# VLAN 10 — Servidors (sense DHCP, tot és estàtic)
# Els dispositius de la VLAN 10 usen IPs estàtiques configurades
# IPs reservades manualment:
#   192.168.10.10 → Servidor principal (Ubuntu)

