db_host = db
db_port = 5432
db_user = odoo
db_password = False
http_interface = 0.0.0.0
http_port = 8069
longpolling_port = 8072
proxy_mode = True
workers = 2
max_cron_threads = 1
limit_memory_hard = 2684354560   
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
admin_passwd = False
list_db = False
logfile = /var/log/odoo/odoo.log
log_level = warn          
log_db = False
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons